# Generated by Django 4.0.6 on 2022-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='TestItem'),
            preserve_default=False,
        ),
    ]
